### ISSUE TITLE
awaiting `willSponsor` in paymaster API route

### ISSUE THREAD

**Issue by nolanjannotta** [wilsoncusack/wagmi-scw#19]
I've been playing with this code a bit trying to get it to work in my project. As I was testing it I sent random `method` and `params` data in a POST request to `api/paymaster` expecting to get `{"error": "Not a sponsorable operation"}` returned but instead got `{"error": "Method not found"}`. If you await the `willSponsor` function like `if (!await willSponsor({ chainId: parseInt(chainId), entrypoint, userOp }))`   I get `{"error": "Not a sponsorable operation"}` as I was expecting. 

Is it working as intended or should `willSponser` be awaited?

**Comment by wilsoncusack** [comment]
Fix in #24 , thanks!
