### ISSUE TITLE
Paying with Paymaster not working as intended

### ISSUE THREAD

**Issue by Quix44** [wilsoncusack/wagmi-scw#21]
Hey folks, just spun this up to test a sponsored transaction as I want to integrate it into an app. However, even on sepolia im getting the following error:

![Screenshot 2024-06-08 at 10 29 19](https://github.com/wilsoncusack/wagmi-scw/assets/96739828/ceb7ed3d-5a71-40da-8a5a-fb266d83975d)

Im pointing the PAYMASTER_SERVICE_URL to my own paymaster address in coinbase paymaster dashboard for base sepolia. I actually don't even see my POST endpoint (willSponsor) getting hit at all, almost as if the 

capabilities look good:

capabilitiesForChain: {"paymasterService":{"supported":true},"atomicBatch":{"supported":true},"auxiliaryFunds":{"supported":true}}

Raw output of payload:

`{"request":{"transaction":{"nonce":"0x2f","sender":"0x8775d49b8f6eea949d31308e6b66eb9a9e23dc37","initCode":"0x","callData":"0x34fcd5be0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000100000000000000000000000000119ea671030fbf79ab93b436d2e20af6ea469a1900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002440d097c30000000000000000000000008775d49b8f6eea949d31308e6b66eb9a9e23dc3700000000000000000000000000000000000000000000000000000000000000000000000000000000119ea671030fbf79ab93b436d2e20af6ea469a1900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000002440d097c30000000000000000000000008775d49b8f6eea949d31308e6b66eb9a9e23dc3700000000000000000000000000000000000000000000000000000000","maxPriorityFeePerGas":"0xf4240","maxFeePerGas":"0xf4362","paymasterAndData":"0xf5d253b62543c6ef526309d497f619cef95ad43000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000686d968ce3d80036a661cf695bd992b5ab33d6a3e498ffea1ee5d213c7a9e7bb05db5b6ec1e7982ac918963268422a81f1f38403429d6c9006b4acaecd9269c31c","preVerificationGas":"0x4da4e","verificationGasLimit":"0x906bf","callGasLimit":"0x1e602","additionalParameters":{"baseFeePerGas":"0x11c"}},"dappURL":"http://localhost:3000"},"result":{"notices":[{"level":"INFO","i18nKey":"","localizedMessage":"","sourceCoordinate":"SOURCE_COORDINATE_UNKNOWN","sourceCoordinateIndex":0,"noticeType":"NOTICE_TYPE_6"}],"decodedTx":{"blockchain":"BLOCKCHAIN_BASE_SEPOLIA","operations":[{"operationType":"ITEM_TRANSFER","itemTransfer":{"contractAddress":"0x119Ea671030FBf79AB93b436D2E20af6ea469a19","fromAddress":"0x0000000000000000000000000000000000000000","toAddress":"0x8775d49b8F6eeA949D31308e6B66Eb9a9E23Dc37","tokenId":"15153","collection":{"name":"Unknown","imageUrl":""},"item":{"tokenId":"15153","imageUrl":"","name":"NFT #15153","collectionId":""},"quantity":"","quantityRange":null},"validity":null,"attributes":[]},{"operationType":"ITEM_TRANSFER","itemTransfer":{"contractAddress":"0x119Ea671030FBf79AB93b436D2E20af6ea469a19","fromAddress":"0x0000000000000000000000000000000000000000","toAddress":"0x8775d49b8F6eeA949D31308e6B66Eb9a9E23Dc37","tokenId":"15154","collection":{"name":"Unknown","imageUrl":""},"item":{"tokenId":"15154","imageUrl":"","name":"NFT #15154","collectionId":""},"quantity":"","quantityRange":null},"validity":null,"attributes":[]}],"addresses":[{"address":"0x0000000000000000000000000000000000000000","attributes":[]},{"address":"0x119Ea671030FBf79AB93b436D2E20af6ea469a19","attributes":[]},{"address":"0x8775d49b8F6eeA949D31308e6B66Eb9a9E23Dc37","attributes":[]}],"contracts":[],"hints":[],"raw":"eyJub25jZSI6IjB4MmYiLCJzZW5kZXIiOiIweDg3NzVkNDliOGY2ZWVhOTQ5ZDMxMzA4ZTZiNjZlYjlhOWUyM2RjMzciLCJpbml0Q29kZSI6IjB4IiwiY2FsbERhdGEiOiIweDM0ZmNkNWJlMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExOWVhNjcxMDMwZmJmNzlhYjkzYjQzNmQyZTIwYWY2ZWE0NjlhMTkwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA2MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjQ0MGQwOTdjMzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDg3NzVkNDliOGY2ZWVhOTQ5ZDMxMzA4ZTZiNjZlYjlhOWUyM2RjMzcwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDExOWVhNjcxMDMwZmJmNzlhYjkzYjQzNmQyZTIwYWY2ZWE0NjlhMTkwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA2MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMjQ0MGQwOTdjMzAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDg3NzVkNDliOGY2ZWVhOTQ5ZDMxMzA4ZTZiNjZlYjlhOWUyM2RjMzcwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsIm1heFByaW9yaXR5RmVlUGVyR2FzIjoiMHhmNDI0MCIsIm1heEZlZVBlckdhcyI6IjB4ZjQzNjIiLCJwYXltYXN0ZXJBbmREYXRhIjoiMHhmNWQyNTNiNjI1NDNjNmVmNTI2MzA5ZDQ5N2Y2MTljZWY5NWFkNDMwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA2ODZkOTY4Y2UzZDgwMDM2YTY2MWNmNjk1YmQ5OTJiNWFiMzNkNmEzZTQ5OGZmZWExZWU1ZDIxM2M3YTllN2JiMDVkYjViNmVjMWU3OTgyYWM5MTg5NjMyNjg0MjJhODFmMWYzODQwMzQyOWQ2YzkwMDZiNGFjYWVjZDkyNjljMzFjIiwicHJlVmVyaWZpY2F0aW9uR2FzIjoiMHg0ZGE0ZSIsInZlcmlmaWNhdGlvbkdhc0xpbWl0IjoiMHg5MDZiZiIsImNhbGxHYXNMaW1pdCI6IjB4MWU2MDIiLCJhZGRpdGlvbmFsUGFyYW1ldGVycyI6eyJiYXNlRmVlUGVyR2FzIjoiMHgxMWMifX0=","from":"0x8775d49b8f6eea949d31308e6b66eb9a9e23dc37","overriddenBlockheight":"","domain":"http://localhost:3000","entrypoint":"0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789","attributes":[]}}}`

**Comment by wilsoncusack** [comment]
Hi @Quix44 I think this might fix https://github.com/wilsoncusack/wagmi-scw/pull/22

**Comment by Quix44** [comment]
> Hi @Quix44 I think this might fix #22

Unfortunately not - works fine on your vercel link, just simply doesnt work with my own paymaster URL. Its almost like the POST to the willSponsor never actually happens. Like capabilities are not being respected by writeContracts, they are defined and the value is pointing to the api route.

**Comment by Quix44** [comment]
Note - just updated to permissionless latest (0.1.31) and it appears to be working when I run my app in vercel. Not working on localhost tho.

**Comment by wilsoncusack** [comment]
@Quix44 not working on localhost is expected: our window has no way to reach your localhost :)
